### ISSUE TITLE
Fatal errors from leveldown's gyp on install

### ISSUE THREAD

**Issue by bfred-it** [christophercliff/caisson#8]
I can't install caisson on my computer in any node version, tried v0.12, v5 and v6.2.1

Log: http://pastie.org/10869023
Colored log: http://i.imgur.com/MeAWiUG.png http://i.imgur.com/5Lj3g9F.png

**Comment by christophercliff** [comment]
This project hasn't been maintained since node v0.10. I recommend you use [AWS SDK for JavaScript in Node.js](https://aws.amazon.com/sdk-for-node-js/) or [AWS Command Line Interface](https://aws.amazon.com/cli/) instead.

**Comment by bfred-it** [comment]
It'd be great to say that somewhere though. Perhaps you could run this too:

```sh
npm deprecate caisson@"*" "Deprecated. Use AWS SDK for JavaScript instead"
```
